# Configuration Nixpacks pour Railway - Serveur Node.js

[phases.setup]
nixPkgs = ["nodejs_18", "python3", "pkg-config", "cairo", "pango", "libjpeg", "giflib", "librsvg", "pixman"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'No build step needed for Node.js server'"]

[start]
cmd = "node index.js"